/**
 * COMPLETE SEMANTIC MAPPING - CLASS 1 QUALITY STANDARD
 * All 26 core variables mapped to each of 13 semantic types
 * This is the definitive reference for full semantic renaming
 */

const COMPLETE_SEMANTIC_MAPPING = {
  // 1. watchedValue (watch, listener, subscr, notify, value, state, change)
  'watchedValue': {
    e: 'watchedValue_e',
    s: 'watchedValue_s',
    n: 'watchedValue_n',
    a: 'watchedValue_a',
    t: 'watchedValue_t',
    o: 'watchedValue_o',
    r: 'watchedValue_r',
    l: 'watchedValue_l',
    i: 'watchedValue_i',
    c: 'watchedValue_c',
    h: 'watchedValue_h',
    d: 'watchedValue_d',
    u: 'watchedValue_u',
    p: 'watchedValue_p',
    m: 'watchedValue_m',
    g: 'watchedValue_g',
    f: 'watchedValue_f',
    v: 'watchedValue_v',
    b: 'watchedValue_b',
    w: 'watchedValue_w',
    x: 'watchedValue_x',
    k: 'watchedValue_k',
    z: 'watchedValue_z',
    j: 'watchedValue_j',
    y: 'watchedValue_y',
    q: 'watchedValue_q'
  },

  // 2. series (series, chart, data, plot, bar, line, candle)
  'series': {
    e: 'series_e',
    s: 'series_s',
    n: 'series_n',
    a: 'series_a',
    t: 'series_t',
    o: 'series_o',
    r: 'series_r',
    l: 'series_l',
    i: 'series_i',
    c: 'series_c',
    h: 'series_h',
    d: 'series_d',
    u: 'series_u',
    p: 'series_p',
    m: 'series_m',
    g: 'series_g',
    f: 'series_f',
    v: 'series_v',
    b: 'series_b',
    w: 'series_w',
    x: 'series_x',
    k: 'series_k',
    z: 'series_z',
    j: 'series_j',
    y: 'series_y',
    q: 'series_q'
  },

  // 3. dataSource (data, source, fetch, provider, stream, request, response)
  'dataSource': {
    e: 'dataSource_e',
    s: 'dataSource_s',
    n: 'dataSource_n',
    a: 'dataSource_a',
    t: 'dataSource_t',
    o: 'dataSource_o',
    r: 'dataSource_r',
    l: 'dataSource_l',
    i: 'dataSource_i',
    c: 'dataSource_c',
    h: 'dataSource_h',
    d: 'dataSource_d',
    u: 'dataSource_u',
    p: 'dataSource_p',
    m: 'dataSource_m',
    g: 'dataSource_g',
    f: 'dataSource_f',
    v: 'dataSource_v',
    b: 'dataSource_b',
    w: 'dataSource_w',
    x: 'dataSource_x',
    k: 'dataSource_k',
    z: 'dataSource_z',
    j: 'dataSource_j',
    y: 'dataSource_y',
    q: 'dataSource_q'
  },

  // 4. priceDataSource (price, quote, tick, feed, market, symbol, data)
  'priceDataSource': {
    e: 'priceDataSource_e',
    s: 'priceDataSource_s',
    n: 'priceDataSource_n',
    a: 'priceDataSource_a',
    t: 'priceDataSource_t',
    o: 'priceDataSource_o',
    r: 'priceDataSource_r',
    l: 'priceDataSource_l',
    i: 'priceDataSource_i',
    c: 'priceDataSource_c',
    h: 'priceDataSource_h',
    d: 'priceDataSource_d',
    u: 'priceDataSource_u',
    p: 'priceDataSource_p',
    m: 'priceDataSource_m',
    g: 'priceDataSource_g',
    f: 'priceDataSource_f',
    v: 'priceDataSource_v',
    b: 'priceDataSource_b',
    w: 'priceDataSource_w',
    x: 'priceDataSource_x',
    k: 'priceDataSource_k',
    z: 'priceDataSource_z',
    j: 'priceDataSource_j',
    y: 'priceDataSource_y',
    q: 'priceDataSource_q'
  },

  // 5. logger (log, debug, info, warn, error, level, console)
  'logger': {
    e: 'logger_e',
    s: 'logger_s',
    n: 'logger_n',
    a: 'logger_a',
    t: 'logger_t',
    o: 'logger_o',
    r: 'logger_r',
    l: 'logger_l',
    i: 'logger_i',
    c: 'logger_c',
    h: 'logger_h',
    d: 'logger_d',
    u: 'logger_u',
    p: 'logger_p',
    m: 'logger_m',
    g: 'logger_g',
    f: 'logger_f',
    v: 'logger_v',
    b: 'logger_b',
    w: 'logger_w',
    x: 'logger_x',
    k: 'logger_k',
    z: 'logger_z',
    j: 'logger_j',
    y: 'logger_y',
    q: 'logger_q'
  },

  // 6. config (config, settings, options, preference, setup, initialize)
  'config': {
    e: 'config_e',
    s: 'config_s',
    n: 'config_n',
    a: 'config_a',
    t: 'config_t',
    o: 'config_o',
    r: 'config_r',
    l: 'config_l',
    i: 'config_i',
    c: 'config_c',
    h: 'config_h',
    d: 'config_d',
    u: 'config_u',
    p: 'config_p',
    m: 'config_m',
    g: 'config_g',
    f: 'config_f',
    v: 'config_v',
    b: 'config_b',
    w: 'config_w',
    x: 'config_x',
    k: 'config_k',
    z: 'config_z',
    j: 'config_j',
    y: 'config_y',
    q: 'config_q'
  },

  // 7. handler (handle, process, execute, event, perform, action)
  'handler': {
    e: 'handler_e',
    s: 'handler_s',
    n: 'handler_n',
    a: 'handler_a',
    t: 'handler_t',
    o: 'handler_o',
    r: 'handler_r',
    l: 'handler_l',
    i: 'handler_i',
    c: 'handler_c',
    h: 'handler_h',
    d: 'handler_d',
    u: 'handler_u',
    p: 'handler_p',
    m: 'handler_m',
    g: 'handler_g',
    f: 'handler_f',
    v: 'handler_v',
    b: 'handler_b',
    w: 'handler_w',
    x: 'handler_x',
    k: 'handler_k',
    z: 'handler_z',
    j: 'handler_j',
    y: 'handler_y',
    q: 'handler_q'
  },

  // 8. delegate (delegate, proxy, forward, relay, distribute)
  'delegate': {
    e: 'delegate_e',
    s: 'delegate_s',
    n: 'delegate_n',
    a: 'delegate_a',
    t: 'delegate_t',
    o: 'delegate_o',
    r: 'delegate_r',
    l: 'delegate_l',
    i: 'delegate_i',
    c: 'delegate_c',
    h: 'delegate_h',
    d: 'delegate_d',
    u: 'delegate_u',
    p: 'delegate_p',
    m: 'delegate_m',
    g: 'delegate_g',
    f: 'delegate_f',
    v: 'delegate_v',
    b: 'delegate_b',
    w: 'delegate_w',
    x: 'delegate_x',
    k: 'delegate_k',
    z: 'delegate_z',
    j: 'delegate_j',
    y: 'delegate_y',
    q: 'delegate_q'
  },

  // 9. canvasRendering (canvas, render, draw, paint, graphics, bitmap)
  'canvasRendering': {
    e: 'canvasRendering_e',
    s: 'canvasRendering_s',
    n: 'canvasRendering_n',
    a: 'canvasRendering_a',
    t: 'canvasRendering_t',
    o: 'canvasRendering_o',
    r: 'canvasRendering_r',
    l: 'canvasRendering_l',
    i: 'canvasRendering_i',
    c: 'canvasRendering_c',
    h: 'canvasRendering_h',
    d: 'canvasRendering_d',
    u: 'canvasRendering_u',
    p: 'canvasRendering_p',
    m: 'canvasRendering_m',
    g: 'canvasRendering_g',
    f: 'canvasRendering_f',
    v: 'canvasRendering_v',
    b: 'canvasRendering_b',
    w: 'canvasRendering_w',
    x: 'canvasRendering_x',
    k: 'canvasRendering_k',
    z: 'canvasRendering_z',
    j: 'canvasRendering_j',
    y: 'canvasRendering_y',
    q: 'canvasRendering_q'
  },

  // 10. chartManager (chart, manage, control, state, layout)
  'chartManager': {
    e: 'chartManager_e',
    s: 'chartManager_s',
    n: 'chartManager_n',
    a: 'chartManager_a',
    t: 'chartManager_t',
    o: 'chartManager_o',
    r: 'chartManager_r',
    l: 'chartManager_l',
    i: 'chartManager_i',
    c: 'chartManager_c',
    h: 'chartManager_h',
    d: 'chartManager_d',
    u: 'chartManager_u',
    p: 'chartManager_p',
    m: 'chartManager_m',
    g: 'chartManager_g',
    f: 'chartManager_f',
    v: 'chartManager_v',
    b: 'chartManager_b',
    w: 'chartManager_w',
    x: 'chartManager_x',
    k: 'chartManager_k',
    z: 'chartManager_z',
    j: 'chartManager_j',
    y: 'chartManager_y',
    q: 'chartManager_q'
  },

  // 11. lineToolManager (line, tool, draw, manage, user)
  'lineToolManager': {
    e: 'lineToolManager_e',
    s: 'lineToolManager_s',
    n: 'lineToolManager_n',
    a: 'lineToolManager_a',
    t: 'lineToolManager_t',
    o: 'lineToolManager_o',
    r: 'lineToolManager_r',
    l: 'lineToolManager_l',
    i: 'lineToolManager_i',
    c: 'lineToolManager_c',
    h: 'lineToolManager_h',
    d: 'lineToolManager_d',
    u: 'lineToolManager_u',
    p: 'lineToolManager_p',
    m: 'lineToolManager_m',
    g: 'lineToolManager_g',
    f: 'lineToolManager_f',
    v: 'lineToolManager_v',
    b: 'lineToolManager_b',
    w: 'lineToolManager_w',
    x: 'lineToolManager_x',
    k: 'lineToolManager_k',
    z: 'lineToolManager_z',
    j: 'lineToolManager_j',
    y: 'lineToolManager_y',
    q: 'lineToolManager_q'
  },

  // 12. bitmapCoordinatesPane (bitmap, coordinate, position, pane, view)
  'bitmapCoordinatesPane': {
    e: 'bitmapCoordinatesPane_e',
    s: 'bitmapCoordinatesPane_s',
    n: 'bitmapCoordinatesPane_n',
    a: 'bitmapCoordinatesPane_a',
    t: 'bitmapCoordinatesPane_t',
    o: 'bitmapCoordinatesPane_o',
    r: 'bitmapCoordinatesPane_r',
    l: 'bitmapCoordinatesPane_l',
    i: 'bitmapCoordinatesPane_i',
    c: 'bitmapCoordinatesPane_c',
    h: 'bitmapCoordinatesPane_h',
    d: 'bitmapCoordinatesPane_d',
    u: 'bitmapCoordinatesPane_u',
    p: 'bitmapCoordinatesPane_p',
    m: 'bitmapCoordinatesPane_m',
    g: 'bitmapCoordinatesPane_g',
    f: 'bitmapCoordinatesPane_f',
    v: 'bitmapCoordinatesPane_v',
    b: 'bitmapCoordinatesPane_b',
    w: 'bitmapCoordinatesPane_w',
    x: 'bitmapCoordinatesPane_x',
    k: 'bitmapCoordinatesPane_k',
    z: 'bitmapCoordinatesPane_z',
    j: 'bitmapCoordinatesPane_j',
    y: 'bitmapCoordinatesPane_y',
    q: 'bitmapCoordinatesPane_q'
  },

  // 13. seriesBarFunction (series, bar, function, chart, calculate)
  'seriesBarFunction': {
    e: 'seriesBarFunction_e',
    s: 'seriesBarFunction_s',
    n: 'seriesBarFunction_n',
    a: 'seriesBarFunction_a',
    t: 'seriesBarFunction_t',
    o: 'seriesBarFunction_o',
    r: 'seriesBarFunction_r',
    l: 'seriesBarFunction_l',
    i: 'seriesBarFunction_i',
    c: 'seriesBarFunction_c',
    h: 'seriesBarFunction_h',
    d: 'seriesBarFunction_d',
    u: 'seriesBarFunction_u',
    p: 'seriesBarFunction_p',
    m: 'seriesBarFunction_m',
    g: 'seriesBarFunction_g',
    f: 'seriesBarFunction_f',
    v: 'seriesBarFunction_v',
    b: 'seriesBarFunction_b',
    w: 'seriesBarFunction_w',
    x: 'seriesBarFunction_x',
    k: 'seriesBarFunction_k',
    z: 'seriesBarFunction_z',
    j: 'seriesBarFunction_j',
    y: 'seriesBarFunction_y',
    q: 'seriesBarFunction_q'
  }
};

module.exports = COMPLETE_SEMANTIC_MAPPING;
