#!/usr/bin/env node

/**
 * Webpack Module Splitter for TradingView Charting Library
 * 
 * This script splits the large library bundle into individual module files
 * based on webpack's module pattern: MODULE_ID:(e,t,i)=>{...}
 * 
 * Usage: node split-library.js
 */

const fs = require('fs');
const path = require('path');

// Configuration
const INPUT_FILE = path.join(__dirname, 'bundles/library.15664647653f41254b4d.js');
const OUTPUT_DIR = path.join(__dirname, 'modules');
// Module pattern: ,MODULE_ID:PARAMS=>{
const MODULE_PATTERN = /,(\d+):([a-z]+)=>\{/g;

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  console.log(`✓ Created output directory: ${OUTPUT_DIR}`);
}

// Read the library file
console.log(`📖 Reading ${INPUT_FILE}...`);
const content = fs.readFileSync(INPUT_FILE, 'utf-8');
console.log(`✓ File size: ${(content.length / 1024 / 1024).toFixed(2)} MB`);

// Find all module boundaries
const modules = [];
let match;

while ((match = MODULE_PATTERN.exec(content)) !== null) {
  const moduleId = match[1];
  const moduleStart = match.index + 1; // +1 to include the comma
  
  if (modules.length > 0) {
    // Set end position for previous module
    const prevModule = modules[modules.length - 1];
    prevModule.end = moduleStart - 1;
  }
  
  modules.push({
    id: moduleId,
    start: moduleStart,
    end: null // Will be set by next iteration
  });
}

// Set end position for last module
if (modules.length > 0) {
  const lastModule = modules[modules.length - 1];
  lastModule.end = content.length;
}

console.log(`✓ Found ${modules.length} modules`);

// Write each module to a separate file
console.log(`\n✂️  Splitting modules...`);
let totalSize = 0;
let minSize = Infinity;
let maxSize = 0;
let minId = null;
let maxId = null;

modules.forEach((module, index) => {
  const moduleCode = content.substring(module.start, module.end);
  const outputPath = path.join(OUTPUT_DIR, `module.${module.id}.js`);
  
  fs.writeFileSync(outputPath, moduleCode, 'utf-8');
  
  const size = moduleCode.length;
  totalSize += size;
  
  if (size < minSize) {
    minSize = size;
    minId = module.id;
  }
  if (size > maxSize) {
    maxSize = size;
    maxId = module.id;
  }
  
  // Log progress every 50 modules
  if ((index + 1) % 50 === 0) {
    console.log(`  Processed ${index + 1}/${modules.length} modules...`);
  }
});

// Create index file
const indexContent = `// TradingView Charting Library - Module Index
// Auto-generated by split-library.js
// Total modules: ${modules.length}

const modules = {
${modules.map(m => `  ${m.id}: () => require('./module.${m.id}.js'),`).join('\n')}
};

module.exports = modules;
`;

const indexPath = path.join(OUTPUT_DIR, 'index.js');
fs.writeFileSync(indexPath, indexContent, 'utf-8');

// Print summary
console.log('\n✅ Splitting complete!\n');
console.log('📊 Summary:');
console.log(`  Total modules: ${modules.length}`);
console.log(`  Output directory: ${OUTPUT_DIR}`);
console.log(`  Total size: ${(totalSize / 1024 / 1024).toFixed(2)} MB`);
console.log(`  Average module size: ${(totalSize / modules.length / 1024).toFixed(2)} KB`);
console.log(`  Smallest module: ${minId} (${(minSize / 1024).toFixed(2)} KB)`);
console.log(`  Largest module: ${maxId} (${(maxSize / 1024).toFixed(2)} KB)`);
console.log(`\n📁 Files created:`);
console.log(`  - ${modules.length} module files (module.ID.js)`);
console.log(`  - 1 index file (index.js)`);
console.log(`\n🚀 Next steps:`);
console.log(`  1. Review modules in ${OUTPUT_DIR}`);
console.log(`  2. Process individual modules for beautification`);
console.log(`  3. Use index.js to understand module dependencies`);
